### ISSUE TITLE
Question about submission

### ISSUE THREAD

**Issue by konyul** [SPengLiang/DID-M3D#1]
I want to know whether this paper is accepted to ECCV 2022
thank you.

**Comment by SPengLiang** [comment]
Yeah, it is accepted to ECCV 2022.

**Comment by konyul** [comment]
thank you, and is "Lidar Point Cloud Guided Monocular 3D Object Detection" accepted too? I see the same author wrote them.

**Comment by SPengLiang** [comment]
Yeah, and we will upate the version in arXiv next week.

**Comment by konyul** [comment]
Thank you
