### ISSUE TITLE
about waymo dataset

### ISSUE THREAD

**Issue by zyrant** [SPengLiang/DID-M3D#11]
Hi, thanks for your work and the code.
The result on the waymo dataset is presented in the supplementary material in the paper and the result is also very good.
My question is, do you have any plan to make the code part of the waymo public?

thanks

**Comment by SPengLiang** [comment]
Thanks for your interest in this work. Similar to CaDDN, we also convert Waymo data format to KITTI for convenience in training. Most codes are the same except the dataloader. Unfortunately, I am currently very busy, so I have no plan to support Waymo dataset in a short time.

**Comment by zyrant** [comment]
Get it, thank you.
