### ISSUE TITLE
the difference between of original paper and this repo	

### ISSUE THREAD

**Issue by zyrant** [SPengLiang/DID-M3D#14]
Hi

I'm curious why the result `Car@BEV IoU=0.7[33.91,24.00,19.52] / Car@3D IoU=0.7[33.91 ,24.00, 19.52]` in this repo is better than the result `Car@BEV IoU=0.7[31.10,22.76, 19.50] / Car@3D IoU=0.7[25.38,17.07,14.06]` of original paper? 
Is there any difference that makes this improve?

Thanks.

**Comment by SPengLiang** [comment]
Sorry for the late reply. The released codebase is our re-implementation of the original code in the paper. The core code and idea are the same.

**Comment by zyrant** [comment]
thx, it is an interesting thing.
