### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by alsrb4446** [SPengLiang/DID-M3D#15]
Hi. First of all, thank you for great work!
I want to reproduce your result in paper. But model has non-deterministic algorithm, i.e AdaptiveAvgPool2d or seed.
How did you get the results of your paper? Did you write down the highest value after several experiments? I wonder how the Ablation Study was conducted.

Thank you.

**Comment by SPengLiang** [comment]
Sorry for the late reply. We use the average accuracy of several experiments for the ablation.
