### ISSUE TITLE
Run inference on a video frame by frame

### ISSUE THREAD

**Issue by y0088766** [SPengLiang/DID-M3D#16]
Thank you for your amazing work! I am kind of new to the 3d object detection topic. So far, i was able to test your pretrained did and got similar results to the ones you described. With the help of the kitti devkit i was able to visualize the according results.
Now i want to to test the pretrained model on new images, e.g. images from frame after frame video input and visualize the according outputs.
What do i have to do so did takes a single image (maybe together with the information about the image size) as input?

**Comment by SPengLiang** [comment]
Very sorry for the late reply. Thanks for your interest in this work! Unfortunately, the current codebase cannot support a single image input directly. You can modify "train_val.py" and the kitti dataloader to achieve your goal (e.g., add a test/demo function to support a single image input).

**Comment by y0088766** [comment]
I ran into some issues in between but I finally managed to do so. Thank you!
