### ISSUE TITLE
There is error between eval mAP during training and inference mAP after training

### ISSUE THREAD

**Issue by Senwang98** [SPengLiang/DID-M3D#17]
@SPengLiang 
Sorry to disturb you again, but I indeed meet one problem and could you help me?

When I training DID-M3D, I let model eval per 10 epoches, and then I get mAP=1.82925 at epoch10.

After training, I use the command `CUDA_VISIBLE_DEVICES=0,1,2,3 python tools/train_val.py --config config/kitti.yaml -e` to see the performance of `checkpoint_10.pth`.

Unfortunately, two mAPs are different.

(即，训练中的eval结果与我用-e指令得到的结果有误差，不知道这是不是正常，好奇到底是什么地方有问题，因为GUPNet没出现这个问题，怀疑是mmdet3d的eval.py？)

![image](https://user-images.githubusercontent.com/23122139/207595003-e54b15ac-03ff-4a8f-84f2-d4c5d9becb34.png)

**Comment by SPengLiang** [comment]
Sorry for the late reply! This slight difference is caused by the flag in the training config: drop_last_val, which sets "drop_last" of the val dataloader.

**Comment by Senwang98** [comment]
@SPengLiang 
Okay, I got it.
