### ISSUE TITLE
Non-deterministic algorithm

### ISSUE THREAD

**Issue by alsrb4446** [SPengLiang/DID-M3D#18]
Thank you for your great work!

I know that the monocular 3D object detection uses non-deterministic algorithm. Even if the seed is fixed, the training results are not consistent. Is this true?

And do you know which non-deterministic algorithm is used where in the code?

**Comment by Senwang98** [comment]
@alsrb4446 
I think I can give you answer, uncertainty theory will not affect training result if you fix seed.
The reason why DID-M3D can't be consistent is that DID-M3D and GUPNet use `ROI-align` op, which is unstable.
If you use other monocular detector, you will find their training result is consistent. Any model using ROI-align will be unconsistent.

**Comment by alsrb4446** [comment]
Thanks a lot for your reply!

**Comment by dragonfly606** [comment]
@Senwang98 I have also been troubled by this problem for a long time. I never thought I would see the possible answer here. 
Is it the same for monoflex?

**Comment by Senwang98** [comment]
@Ydragon-ylf 
I haven't used MonoFlex for a while. I have the impression that although MonoFlex does not use ROI-Align, its truncation module is random, so MonoFlex cannot be reproduced stably. I have forgotten what caused it. , but I'm pretty sure it's a problem with the truncated module.

**Comment by dragonfly606** [comment]
> @Ydragon-ylf I haven't used MonoFlex for a while. I have the impression that although MonoFlex does not use ROI-Align, its truncation module is random, so MonoFlex cannot be reproduced stably. I have forgotten what caused it. , but I'm pretty sure it's a problem with the truncated module.

Thank you very much for your timely reply!
