### ISSUE TITLE
question

### ISSUE THREAD

**Issue by mikasazgx** [SPengLiang/DID-M3D#2]
the code is fine, but i have a question
when i visualize 3D bbox
i find the kitti_utils.py has the function generate_corners3d
![Screenshot from 2022-07-28 18-08-27](https://user-images.githubusercontent.com/26949230/181480511-efb4c332-d51d-4a68-95b7-d0ecd3490eb5.png)
 
why y_corners is [0, 0, 0, 0, -h, -h, -h, -h] instead of [h/2, h/2, h/2, h/2, -h/2, -h/2, -h/2, -h/2]
ask for help
thanks!!!!

this is my visualize result
![Screenshot from 2022-07-28 18-10-59](https://user-images.githubusercontent.com/26949230/181480956-d3496566-d4fb-4b14-814a-da2c749fa939.png)
its fine use y_corners = [0, 0, 0, 0, -h, -h, -h, -h]

**Comment by SPengLiang** [comment]
Thanks for your interest in this work.  It is because y coordinate in KITTI labels is not the 3D box center, but the 3D box bottom center.

**Comment by mikasazgx** [comment]
thanks a lot
