### ISSUE TITLE
Is ” visible depth” = 2D projected Lidar depth？

### ISSUE THREAD

**Issue by Senwang98** [SPengLiang/DID-M3D#21]
@SPengLiang 
Hello, bro.
I began to be unsure about the meaning of the depth of the KITTI label. 
Figure 1 of DID-M3D shows that the visible depth is the vertical depth under the BEV perspective, but the depth of the lidar is not vertical. 
Can the two be directly equivalent? 
I have not thought about this question before.
（DID-M3D图1的三种深度都是垂直于相机的深度，激光雷达的深度应该不是垂直的，请问kitti官方是手动根据三角形计算垂直深度作为标注深度的吗？因为我最近在arxiv上看到这张图，思路跟DID-M3D很像，但他不是垂直距离）
![image](https://user-images.githubusercontent.com/23122139/217590910-77c83262-7824-4a5b-b155-681574e9703e.png)

**Comment by SPengLiang** [comment]
Hi bro~ Depths in KITTI are from LiDAR points，which are captured under LiDAR coordinate system and then transformed to camera coordinate system and then projected onto the image. The depth of the lidar/camera is vertical. KITTI官方给的标注深度其实就是垂直距离，没有涉及到三角形，因为lidar给的深度就是体现在坐标里面（lidar坐标系下的x坐标)，坐标转换过去就好。深度这个概念一般都是垂直的

**Comment by Senwang98** [comment]
@SPengLiang 
了解了，我之前理解的是对的，我受arxiv这篇论文影响了，这篇论文似乎是用三角形的斜边了。
感谢大佬
