### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by Xiaolong-RRL** [SPengLiang/DID-M3D#23]
Thanks for you nice work!!

But I'm still confused about how you visualize this figure (Fig.5 in paper) ?

![image](https://user-images.githubusercontent.com/74476562/219672279-977162eb-8e7f-4a0a-8c43-062fe90f4647.png)

**Comment by SPengLiang** [comment]
Sorry for the late reply! We use mayavi to visualize the point cloud (only used in visualization) and 3D detection results. 
You can refer to this codebase (https://github.com/kuixu/kitti_object_vis) for visualization.

**Comment by Xiaolong-RRL** [comment]
I got it! Thanks!!

**Comment by SPengLiang** [comment]
You can also use open3d for visualization. You can refer to this codebase  https://github.com/chaomath/open3d-kitti-visualization. Both mavayi and open3d can generate similar results.

**Comment by Xiaolong-RRL** [comment]
OK~ I will try both, thank you very much for your enthusiastic reply!!
