### ISSUE TITLE
Visual depth affine transform

### ISSUE THREAD

**Issue by mingyuShin** [SPengLiang/DID-M3D#24]
Thank you for your great research. 

Could you please let me know where I can find the code for augmenting visual depth using affine transforms with scale factor "S_y"?

Thanks

**Comment by SPengLiang** [comment]
Thanks for your interest. The scale factor is at https://github.com/SPengLiang/DID-M3D/blob/2475af69c32b5bd5a716aa14f0c6570fa11a640b/lib/models/DID.py#L175 and is used in https://github.com/SPengLiang/DID-M3D/blob/2475af69c32b5bd5a716aa14f0c6570fa11a640b/lib/models/DID.py#L182

**Comment by mingyuShin** [comment]
Thank you for your replay.
