### ISSUE TITLE
For the submission on KITTI 3D OD benchmark

### ISSUE THREAD

**Issue by mingyuShin** [SPengLiang/DID-M3D#27]
Hello. Thank you for the great research. 

I have two questions.

1. When submitting to the KITTI dataset benchmark, is it correct to use all 7,481 images in the training folder for training? 

2. If so, could you please explain how you validated for submission to the test? 

Thank you.

**Comment by SPengLiang** [comment]
Hi, thanks for your interest in our work. 
1. Yes, you are right.
2. When evaluating on KITTI website, you can use the final ckpt or build a small validation set (e.g., 100 samples) for selecting the best one.

**Comment by mingyuShin** [comment]
Thanks a lot for your replying.
