### ISSUE TITLE
how to get the depth_dense

### ISSUE THREAD

**Issue by MillX2021** [SPengLiang/DID-M3D#3]
Thanks for your work.
but i had a question. how to get the depth dense of kitti.
because i only look the image_2 & label_2 & calib in kitti traing dataset

**Comment by SPengLiang** [comment]
You can use a pre-trained depth completion model to generate dense depth maps. To ease the usage, we provided the pre-generated depth maps (https://drive.google.com/file/d/1mlHtG8ZXLfjm0lSpUOXHulGF9fsthRtM/view?usp=sharing) in Readme. You can download and unzip them, and then link/move the folder under "KITTI3D/training/".

**Comment by MillX2021** [comment]
Thanks

**Comment by Senwang98** [comment]
@SPengLiang 
Is this depth map generated by method 'ip_basic', which is used in MonoDistill and CaDDN?

**Comment by SPengLiang** [comment]
No, we didn't try this method. Instead, we use the depth completion model in https://github.com/JUGGHM/PENet_ICRA2021.

**Comment by Senwang98** [comment]
@SPengLiang 
Okay, I use ip_basic to train and I find the performance is a little lower.

**Comment by SPengLiang** [comment]
If you want to use your dense depth maps for training, two aspects should be noticed:   1. the depth map is dense. if there are some invalid areas (namely, 0), the depth transformation in dataloader should be carefully modified; 2. the filled depth should be much precise (visual depth is not very sensitive to less accurate filled depth, but attribute depth is sensitive). Hope this can help you.

**Comment by Senwang98** [comment]
@SPengLiang 
Thanks for your kind suggestions, I got it.

**Comment by yjy4231** [comment]
> No, we didn't try this method. Instead, we use the depth completion model in https://github.com/JUGGHM/PENet_ICRA2021.
May I ask if the model you are using is ENet or PENet?  And is the weight used the pretrain weight provided by the model author's github, or did you train it yourself? If you trained it yourself, can you send me a copy through online storage or other methods? Thank you!
![image](https://github.com/SPengLiang/DID-M3D/assets/52461074/f4a3e406-799d-4091-b465-40343cfe1f25)
