### ISSUE TITLE
Can you provide the visualization code

### ISSUE THREAD

**Issue by yjy4231** [SPengLiang/DID-M3D#30]
Excuse me, could you please provide me with the code for visualizing the results in your paper through online storage or other forms?
![image](https://github.com/SPengLiang/DID-M3D/assets/52461074/b8f9439a-b231-495e-8937-1623141cb021)

**Comment by SPengLiang** [comment]
Thanks for your interest in this work. Please refer to https://github.com/SPengLiang/DID-M3D/issues/23 for the visualization.
