### ISSUE TITLE
The issue

### ISSUE THREAD

**Issue by yjy4231** [SPengLiang/DID-M3D#34]

**Comment by yjy4231** [comment]
The HTL strategy is related to the epoch, and different epoch settings have an impact on the final experimental results。
The epoch in 'config.py' is 150, but in your paper is 200. When you train on trainval set or train set, the epoch should be set?
![image](https://github.com/SPengLiang/DID-M3D/assets/52461074/a8f138e6-61e5-49e2-85a2-596b1ab992cd)
![image](https://github.com/SPengLiang/DID-M3D/assets/52461074/0a53f3da-80da-420e-9efe-df1075104b63)

**Comment by SPengLiang** [comment]
We find that epoch 150 is good enough, and the results with epoch 200 and 150 are close.

**Comment by yjy4231** [comment]
Thanks!
