### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [SPengLiang/DID-M3D#4]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
- ONNX
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/321_DID-M3D

Thank you.

**Comment by SPengLiang** [comment]
Hi, we have added the license, thanks for your interest in this work.

**Comment by PINTO0309** [comment]
Thanks!
