### ISSUE TITLE
Provide pre-generated dense depth and pre-trained model on BaiduYun Disk?

### ISSUE THREAD

**Issue by Deephome** [SPengLiang/DID-M3D#6]
Hi, your work is great! Can you also provide pre-generated dense depth and pre-trained model on BaiduYun Disk?

**Comment by SPengLiang** [comment]
Thanks for your interest. I will upload them to BaiduYun Disk by tomorrow night.

**Comment by SPengLiang** [comment]
I have uploaded the files.   Pre-trained model: https://pan.baidu.com/s/10Q57tDAU5RrUq-bFw3oXmQ  extraction code: 9ean 
 Dense depth: https://pan.baidu.com/s/1KDBnduzCJ4ZtjkpF5tPCmw   extraction code: mge7

**Comment by Deephome** [comment]
Thank you for your reply! I'll have a try!
