### ISSUE TITLE
trained on single gpu

### ISSUE THREAD

**Issue by KuofengGao** [SPengLiang/DID-M3D#7]
Thanks for your great work! I try batchsize 8 on single GPU and other settings remain unchanged.
The results at 100th epoch:
<img width="924" alt="截屏2022-08-06 下午7 57 51" src="https://user-images.githubusercontent.com/97340537/183248001-8be1e1cc-14a2-46a1-a584-c58290cdeeff.png">
The results at 150th epoch:
![image](https://user-images.githubusercontent.com/97340537/183248025-8bafa867-5682-4ce6-830d-ea534cc4f50a.png)
I provide the log file [train.log](https://drive.google.com/file/d/1wLGwmXy9llBOe-8P1jrr1nqoLE7yLbtM/view?usp=sharing) and the config file [kitti_single.yaml](https://drive.google.com/file/d/1gmB4vjGF0P5_9u0jCvnWgm817tip2OYV/view?usp=sharing). Could you please help me? 
My environment is
```
torch==1.1.0
torchvison==0.3.0
cuda==9.0
```
Could you please provide your cuda version?

**Comment by SPengLiang** [comment]
Thanks for your interest in this work! My environment is
torch==1.10.0
torchvison==0.11.1
cuda==11.1

I only tried once to train the model on a single GPU with batch size 8. Please refer the performance and log in  https://github.com/SPengLiang/DID-M3D/issues/5.
I note that your torch and cuda version is a little lower, and I didn't tried with this environment.
You can also try batch size 16 using two or four GPUs, but I am not sure that the results are good.
