### ISSUE TITLE
Question about scale_box2d_masked.

### ISSUE THREAD

**Issue by kaixinbear** [SPengLiang/DID-M3D#8]
Hi, SPengLiang~ Thanks for yout great work !
When I see the code, I find that scale_box2d_masked is not actually the 2D BBoxes, isn't it ?
<img width="438" alt="1659934281(1)" src="https://user-images.githubusercontent.com/33575107/183341709-94344288-6edd-4ce9-bb60-f53fea314480.png">
<img width="511" alt="1659934268(1)" src="https://user-images.githubusercontent.com/33575107/183341686-d0b67cf7-285c-492f-93b6-3578d251c741.png">
For example, if it is [batch_id, x1, y1, x2, y2], then it should be y2 > y1 and x2 > x1, and y2 - y1 should be object'2 2D height.But it seems that scale_box2d_masked is not corresponding to 2D ROIs. 
How to understand this phenomenon?

**Comment by SPengLiang** [comment]
Thanks for your interest in this work. "scale_box2d_masked" is the 2D box rois. I load a pre-trained model and have:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/14855845/183345832-b6df7cdf-02f5-4490-adcd-71a02f3390c5.png">
Your results seem that your model is not trained. Hope this can help you.

**Comment by kaixinbear** [comment]
I have trained the model and run "CUDA_VISIBLE_DEVICES=0 python tools/train_val.py --config config/kitti.yaml -e".
<img width="180" alt="1659938868(1)" src="https://user-images.githubusercontent.com/33575107/183350461-fb978029-cff8-441d-85bd-10975a8cca07.png">
And the trained result seems normal. Could you please tell me how you load the pre-trained model ?

**Comment by SPengLiang** [comment]
You can modify the config file (config/kitti.yaml)
<img width="614" alt="image" src="https://user-images.githubusercontent.com/14855845/183350903-6195f1db-acb9-4e68-81b9-fac4d528fafa.png">
Sorry for this unclarity, I will update the readme to add details of loading the pre-trained model. Thanks for your feedback!

**Comment by kaixinbear** [comment]
I got it! Thanks for your reply!
